spring.datasource.url=jdbc:postgresql://localhost:5432/hk_shop
spring.datasource.username=admin
spring.datasource.password=admin
logging.level.org.springframework.security=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
app.jwtSecret=changeThisToASecureRandomStringWithLengthAtLeast32Chars
app.jwtExpirationMs=900000

# Refresh token
app.refreshTokenExpirationMs=2592000000
app.refreshTokenCookieMaxAgeSeconds=2592000
app.refreshTokenCookieName=refreshToken
